### PR TITLE
Linxia/react client frontend setup

### PR DESCRIPTION
**Pull request by Colaicerei**
please merge Mandy's work so we can pull

### CODE REVIEW

**Comment by Colaicerei** [comment]
i see there are new updates

**Comment by Colaicerei** [comment]
clicked the wrong button:(

**Comment by onelittlekiwi** [comment]
I reopen this branch merge request, so we can merge this branch into the master.

**Comment by Colaicerei** [comment]
great!

**Review by dodoph — APPROVED** [review]

**Pull request merged**
